spring:
  application:
    name: api-generator
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
  datasource:
    druid: # 数据库相关配置，根据实际情况修改
      url: jdbc:mysql://124.221.226.105:3306/seed ?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
      username: qmis
      password: $moP8HUBE2NBdi%R
      driverClassName: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 50
      initialSize: 10
      maxWait: 600000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  redis:
    database: 2
    port: 6389
    host: 10.10.3.194
    password: redis!@#
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # jwt秘钥
  jwt-secret-key: FWf9gEQtjd2JPeI0

generator:
  author: 李升平
  packageName: com.misssyc.seed
  autoRemovePre: true
  tablePrefix: admin